channels:
- conda-forge
dependencies:
- python >=3.9,<3.12
- aimsgb =1.1.1
- ipycanvas =0.13.2
- ipython =8.24.0
- ipywidgets =7.7.1
- jupyterlab =3.6.6
- matplotlib =3.8.4
- nglview =3.0.8
- numpy =1.23.5
- openjdk =22.0.1
- owlready2 =0.46
- pandas =2.2.0
- pyiron_base =0.7.3
- pyiron_atomistics = 0.3.3
- pyiron_gui =0.0.8
- pyiron_ontology =0.1.3
- ryvencore =0.3.1.1
- seaborn =0.13.2
- traitlets =5.14.1
- lammps =2024.02.07
