channels:
- conda-forge
dependencies:
- ipycanvas
- ipython
- ipywidgets == 7.*
- maggma >= 0.57.1
- matplotlib
- nglview <= 3.0.9
- numpy
- owlready2
- pandas
- pyiron_base
- pyiron_atomistics >= 0.2.57
- pyiron_gui >= 0.0.8
- pyiron_ontology == 0.1.3
- ryvencore =0.3.1.1
- seaborn
- traitlets
- python >= 3.8
- lammps
