channels:
- conda-forge
dependencies:
- ipycanvas
- ipython
- ipywidgets == 7.*
- matplotlib
- nglview
- numpy
- owlready2
- pandas
- pyiron_base
- pyiron_atomistics >= 0.2.57
- pyiron_gui >= 0.0.8
- pyiron_ontology == 0.1.3
- ryvencore
- seaborn
- traitlets
- python >= 3.8
- lammps
