channels:
- conda-forge
dependencies:
- ipycanvas
- ipython
- ipywidgets == 7.*
- matplotlib
- nglview
- numpy
- pyiron_base
- pyiron_atomistics >= 0.2.57
- pyiron_gui
- ryvencore
- python >= 3.8
- lammps
