channels:
  - conda-forge
dependencies:
  - sphinx
  - nbsphinx
  - ipywidgets
  - sphinx_rtd_theme
  - pylint
  - Graphviz
  - sphinxcontrib-applehelp
  - seaborn
  - jinja2 <3
  - ipycanvas
  - ipython
  - ipywidgets == 7.*
  - lammps
  - matplotlib
  - nglview
  - numpy
  - pyiron_base
  - pyiron_atomistics >= 0.2.57
  - ryvencore
