channels:
  - conda-forge
dependencies:
  - ipycanvas
  - ipython
  - ipywidgets == 7.*
  - maggma >= 0.57.1
  - matplotlib
  - nglview <= 3.0.9
  - numpy
  - owlready2
  - pandas
  - pyiron_base
  - pyiron_atomistics = 0.5.4
  - pyiron_gui == 0.0.8
  - pyiron_ontology == 0.2.7
  - ryvencore =0.3.1.1
  - seaborn
  - traitlets
