# Description of this workflow

name: "Setup cached mamba"
inputs:
  python-version:
    required: true
    type: string
  env-prefix:
    required: true
    type: string
  env-label:
    required: true
    type: string
  additional-env-file:
    required: false
    type: string
  run-pyironconfig:
    required: false
    type: boolean
    default: false
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v2
  - name: Write environment
    run: |
      if [ "${{ inputs.additional-env-file }}" == "" ]; then
        cp .ci_support/environment.yml environment.yml
      else
        python .ci_support/condamerge.py --base .ci_support/environment.yml --add ${{ inputs.additional-env-file }} > environment.yml
      fi
  - name: Setup Mambaforge
    uses: conda-incubator/setup-miniconda@v2
    with:
      python-version: ${{ inputs.python-version }}
      miniforge-variant: Mambaforge
      channels: conda-forge
      channel-priority: strict
      activate-environment: my-env
      use-mamba: true
  - name: Set cache date and number
    run: |
      echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
      cat .github/variables/cache_number.env >> $GITHUB_ENV
  - uses: actions/cache@v2
    with:
      path: ${{ inputs.env-prefix }}
      key: ${{ inputs.env-label }}-conda-${{ hashFiles('environment.yml') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
    id: cache
  - name: Update environment
    run: mamba env update -n my-env -f environment.yml
    if: steps.cache.outputs.cache-hit != 'true'
  - name: Run pyironconfig
    shell: bash -l {0}
    run: python .ci_support/pyironconfig.py
    if: ${{ inputs.run-pyironconfig }}
  - name: Setup
    shell: bash -l {0}
    run: pip install --no-deps .
