# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  call-build-docs-from-workflow:
    uses: pyiron/pyiron_github/workflows/push-pull-to-main.yml@main
  call-build-docs-from-github-workflow:
    uses: pyiron/pyiron_github/.github/workflows/push-pull-to-main.yml@main
  call-build-docs-from-root:
    uses: pyiron/pyiron_github/push-pull-to-main.yml@main