# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/setup-cached-mamba
      with:
        python-version: '3.10'
        env-prefix: '/usr/share/miniconda3/envs/my-env'
        env-label: 'linux-64-py-3-10'
        additional-env-file: .ci_support/environment-docs.yml
        run-pyironconfig: true
    - name: Documentation
      shell: bash -l {0}
      run: ./.ci_support/build_docs.sh
