# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup environment
      run: |
        python .ci_support/condamerge.py --base .ci_support/environment.yml --add .ci_support/environment-docs.yml > environment.yml
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: '3.10'
        miniforge-variant: Mambaforge
        channels: conda-forge
        channel-priority: strict
        activate-environment: my-env
        use-mamba: true
    - name: Set cache date and number
      run: |
        echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
        if [ -f github/variables/cache_number.env ]; then
          cat .github/variables/cache_number.env >> $GITHUB_ENV
        else
          echo "CACHE_NUMBER=0" >> $GITHUB_ENV 
        fi
    - uses: actions/cache@v2
      with:
        path: /usr/share/miniconda3/envs/my-env
        key: linux-64-py-3-10-conda-${{ hashFiles('environment.yml') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
      id: cache
    - name: Update environment
      run: mamba env update -n my-env -f environment.yml
      if: steps.cache.outputs.cache-hit != 'true'
    - name: Setup
      shell: bash -l {0}
      run: |
        python .ci_support/pyironconfig.py
        pip install --no-deps .
    - name: Documentation
      shell: bash -l {0}
      run: ./.ci_support/build_docs.sh
