# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Notebooks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: pyiron/pyiron_github/actions/build-notebooks@main
      with:
        python-version: '3.10'
        env-prefix: /usr/share/miniconda3/envs/my-env
        env-label: linux-64-py-3-10
