# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Notebooks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: pyiron/pyiron_github/actions/cached-mamba@main
      with:
        python-version: '3.10'
        env-prefix: /usr/share/miniconda3/envs/my-env
        env-label: linux-64-py-3-10
        additional-env-file: .ci_support/environment-notebooks.yml
    - uses: pyiron/pyiron_github/actions/pyiron-config@main
    - name: Tests
      shell: bash -l {0}
      run: ./.ci_support/build_notebooks.sh
