# This runs jobs which pyiron modules should run when a PR is labeled

name: PR labeled

on:
  pull_request:
    types: [labeled]

jobs:
  pr-labeled:
    uses: pyiron/pyiron_github/.github/workflows/pr-labeled.yml@main
    secrets: inherit