# This runs jobs which pyiron modules should run when a PR is labeled

name: PR labeled

on:
  pull_request:
    types: [labeled]

jobs:
  pyiron:
    uses: pyiron/actions/.github/workflows/pr-labeled.yml@46de4039b7c6ea32083e84c5c96b2f38e4ce21b3
    secrets: inherit