# This runs jobs which pyiron modules should run when a PR target is opened

name: PR opened

on:
  pull_request_target:
    types: [opened]

jobs:
  pr-target-opened:
    uses: pyiron/pyiron_github/.github/workflows/pr-target-opened.yml@main
    secrets: inherit