name: Push or Pull to main
description: This runs jobs which pyiron modules should run on pushes or PRs to main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  call-centralized-workflow:
    uses: pyiron/pyiron_github/.github/workflows/push-pull-to-main.yml@main
    secrets: inherit