name: Pip check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        python-version: [3.10]

    steps:
    - uses: actions/checkout@v3
    - uses: pyiron/pyiron_github/actions/cached-mamba@main
      with:
        python-version: '3.10'
        env-prefix: /usr/share/miniconda3/envs/my-env
        env-label: linux-64-py-3-10
    - name: Check
      shell: bash -l {0}
      run: pip check
