name: Pip check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: pyiron/pyiron_github/actions/pip-check@main
      with:
        python-version: '3.10'
        env-prefix: /usr/share/miniconda3/envs/my-env
        env-label: linux-64-py-3-10
