# This runs jobs which pyiron modules should run on release
name: Release

on:
  release:

jobs:
  pyiron_github:
    uses: pyiron/pyiron_github/.github/workflows/release.yml@main
    secrets: inherit